import './globals.css'
import { Inter } from 'next/font/google'
import { UserProvider } from '../context/context.js';
import Footer from '../components/Footer.js';
import Header from '../components/Header.js';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
